### ISSUE TITLE
Use <p> instead of <div> for wrapping text

### ISSUE THREAD

**Issue by griffinlacek** [mandeepsimak/prj-rev-bwfs-tea-cozy#4]
You have some small amounts of text wrapped in a `<div>`, but divs are just used for wrapping related HTML content and not to hold text by itself. They can and do work, but generally if you have text it should go in a text related tag. Here, a `<p>` tag would work better as it's specifically for text and more descriptive.

https://github.com/mandeepsimak/prj-rev-bwfs-tea-cozy/blob/master/Project%20Tea/index.html#L36
https://github.com/mandeepsimak/prj-rev-bwfs-tea-cozy/blob/master/Project%20Tea/index.html#L40
https://github.com/mandeepsimak/prj-rev-bwfs-tea-cozy/blob/master/Project%20Tea/index.html#L44
https://github.com/mandeepsimak/prj-rev-bwfs-tea-cozy/blob/master/Project%20Tea/index.html#L48
https://github.com/mandeepsimak/prj-rev-bwfs-tea-cozy/blob/master/Project%20Tea/index.html#L52

**Comment by mandeepsimak** [comment]
Thanks, updated the file on commit.
